Enricher
GitbarPodcast/Botletter pull request #28
Opened 2021-06-06 17:31 UTC by brainrepo

Extracts title, subtitle, author and image from an article.

2021-06-07 08:31 UTC, JellyBellyDev commented
wouldn't it be better to target the airtable branch for the PR?

2021-06-07 20:46 UTC, brainrepo commented
> wouldn't it be better to target the airtable branch for the PR?

@JellyBellyDev  This feature is not related to the airtable feature. This will work to scrape more information from the link that comes from Telegram. I will be happy to ship it independently. I removed the reference to airtable.

2021-06-08 09:22 UTC, JellyBellyDev requested changes

2021-06-08 09:22 UTC, JellyBellyDev commented on .gitignore
> +.env
add newline at end of file! :P
#linterNazzi

2021-06-10 20:54 UTC, merged